BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE T_FINALIZE_TAB';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE T_MOVE_TAB';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE T_MOVE_REC';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE T_FINALIZE_REC';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

CREATE TYPE T_FINALIZE_REC AS OBJECT (
  FILE_NAME       VARCHAR2(100),
  DOCID           NUMBER,
  STATUS          VARCHAR2(50),
  DESCRIPTION     VARCHAR2(200),
  FY_YEARS        VARCHAR2(50),
  FILESIZE        VARCHAR2(200),
  FILE_EXTENSION  VARCHAR2(40),
  SOURCE_PATH     VARCHAR2(4000),
  SOL_ID          VARCHAR2(8),
  CIFID           VARCHAR2(16),
  FORACID         VARCHAR2(16),
  ACCT_NAME       VARCHAR2(150)
);
/

CREATE TYPE T_MOVE_REC AS OBJECT (
  FILE_NAME    VARCHAR2(100),
  DOCID        NUMBER,
  MOVE_STATUS  VARCHAR2(50),
  DESCRIPTION  VARCHAR2(200),
  FINAL_PATH   VARCHAR2(4000),
  FILESIZE     VARCHAR2(200)
);
/

CREATE TYPE T_FINALIZE_TAB AS TABLE OF T_FINALIZE_REC;
/

CREATE TYPE T_MOVE_TAB AS TABLE OF T_MOVE_REC;
/
